project/mnproject/mnproject/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productapp.urls')),
]

urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/mnproject/productapp/urls.py
from django.conf import urls
from django.urls import path
from . import views


app_name = 'productapp'
urlpatterns = [
    path('products/', views.products, name='products'),
    path('basket/', views.basket, name ='basket'),
    path('', views.home, name='home'),
    path('/basket/<str:id>/', views.addtobasket, name='addtobasket'),
    path('basket/<str:id>/', views.removefrombasket, name='removefrombasket'),
    # path('basket/', views.basket_total, name='basket_total')
]

project/mnproject/productapp/models.py
from django.db import models

class Products(models.Model):
    products_name = models.CharField(max_length=30)
    pub_date = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    note = models.CharField(max_length=200)
    inventory = models.IntegerField(default=1)
    product_pic = models.ImageField(upload_to ='images/', default='images/broken/broken.png')

    def __str__(self):
        if (self.inventory<=0):
            return self.products_name + ' (Out of Stock)'
        return self.products_name

class Basket(models.Model):
    products = models.ForeignKey(Products, on_delete=models.SET_NULL, null=True, blank=True)
    pub_date = models.DateTimeField(auto_now=True)
    amount = models.IntegerField(default=1)


    def __str__(self):
        return str(self.products)

    #price of a item with amount>1
    @property
    def get_total(self):
        total = self.products.price * self.amount
        return total

    #price of a item in basket from products
    def get_price(self):
        price = self.products.price
        return price

project/mnproject/productapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .models import Products, Basket
from django.template import RequestContext
from django.http import HttpResponseRedirect

#Products Html
def products(request):
    products_list = Products.objects.order_by('-pub_date')
    context = {'products_list': products_list,'title': "Products"}
    return render(request, 'productapp/products.html', context)

#Basket Html
def basket(request):
    basket_list = Basket.objects.order_by('-pub_date')
    #total price of the basket items
    total = sum([item.get_total for item in basket_list])
    context = {'basket_list': basket_list, 'total':total,'title': "Basket"}
    return render(request, 'productapp/basket.html', context)

#Home page Html
def home(request):
    products_list = Products.objects.order_by('-pub_date')
    basket_list = Basket.objects.order_by('-pub_date')
    context = {'products_list': products_list,'basket_list': basket_list,'title': "Home"}
    return render(request, 'pages/index.html', context)

#Rendering Images for products
def image(request):
    images = Products()
    variables = RequestContext(request,{'product_pic':images})
    return render(None,'image.html',variables)

#adding products items to basket
def addtobasket(request, id):
    if request.method == 'POST':
        product = Products.objects.get(id=id)
        basket, created = Basket.objects.get_or_create(products=product)
        basket.amount=request.POST['amount']
        basket.save()
        return HttpResponseRedirect(reverse("productapp:basket"))

#removing items from basket
def removefrombasket(request, id):
    if request.method == 'POST':
        product = Basket.objects.get(id=id)
        product.delete()
        return HttpResponseRedirect(reverse("productapp:basket"))

project/mnproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <style>
        *{
            font-family: "Segoe UI",Arial,sans-serif
        }
        body{
            background:url(https://i.pinimg.com/originals/85/6f/31/856f31d9f475501c7552c97dbe727319.jpg);
        }
        .header{
            background-color: #000000;
		    padding: 8px 16px;
		    width: 100% ;
		    position: fixed;
		    z-index: 100;
		    top: 0;
		    left: 0;
            text-align: center;

        }
        .header > div {
    	    display: inline-block;
    	    vertical-align: middle;

        }
        .nav {
    	display: inline-block;
        position: relative;

        }
        .nav__items{
            margin: 0px;
            padding: 0;
            padding-right: 20px;
            list-style: none;
        }
        .nav__item{
            display: inline-block;
            padding-left:8px;
            padding-right:8px;
            font-size: 19px;
            font-weight:bold;
        }
        .nav__item a{
            color:#ffffff;
            text-decoration: none;
        }
        
        .nav__item a:hover {
            color: #ffe4c4;
            /* border-bottom:3px solid #cecece; */
        }
        .nav__item a:active{
            color: #ffe4c4;
            /* border-bottom:3px solid #cecece; */
        }
        .nav__home a{
            color: #ffe4c4;
            text-decoration: none;
            border-bottom:3px solid #ffffff;
        }
        .nav__home a:hover {
            color: #ffffff;
            border-bottom:3px solid #ffe4c4;
        }
        .nav__home a:active{
            color: rgb(255, 255, 255);
            border-bottom:3px solid #ffe4c4;
        }
        .wellcome {
            position: relative;
			padding: 10px;
			margin-top: 10px;
        }
        wellcome > div{
            display: inline-block;
        }
        .wellcome-div-p
        {
            font-size: 50px;
            color: #000000;
		    text-align: center;
            font-weight: bold;
            border-bottom:3px solid #000000;
        }
        .body{
            background-image: url("https://images.ctfassets.net/yr4qj72ki4ky/6G2JeQnM8bsnjgoJBjljCh/f30782e127727ee309ebf87fb59cf446/best-programming-languages-2020-Hero.jpg");
            background-size:cover;
        }
        .products_section{
            position: relative;
            text-align: center;
            margin-top: 80px;
        }
        .products{
            display:inline-block;
            padding: 10px 50px 30px 50px ;
            background-color: rgb(255, 250, 250, 0.9) ;
            margin: 2px 0px 2px 0px;
            border-radius: 10%;
        }
        .products:hover{
            background-color: rgb(255, 250, 250) ;
        }
        .product{
            color: rgb(26, 26, 26);
        }

        /* .button{
            padding: 5px 40px 5px 40px ;
            background-color: #1d2731 ;
            color:white;
        }
        .button:hover{
            background-color: #FFFAFA;
            color: black;
        } */
        .button {
			text-decoration: none;
            font-size: 13px;
            color:white;
			cursor: pointer;
            background-color: #1d2731 ;
            padding: 5px 40px 5px 40px ;
			border-top: 2px solid rgb(100, 100, 100);
			border-left: 2px solid rgb(100, 100, 100);
			border-bottom: 2px solid rgb(20, 20, 20);
			border-right: 2px solid rgb(20, 20, 20);
			border-radius: 0.5px;
			}
		.button:hover{
            background-color: #FFFAFA;
			color: black;
			}
		.button:active{
			border-bottom: 2px solid rgb(100, 100, 100);
			border-right: 2px solid rgb(100, 100, 100);
			border-left: 2px solid rgb(20, 20, 20);
			border-top: 2px solid rgb(20, 20, 20);
		}
        .button_rev{
            text-decoration: none;
            font-size: 13px;
            color:black;
			cursor: pointer;
            background-color: #FFFAFA;
            padding: 5px 40px 5px 40px ;
			border-top: 2px solid rgb(100, 100, 100);
			border-left: 2px solid rgb(100, 100, 100);
			border-bottom: 2px solid rgb(20, 20, 20);
			border-right: 2px solid rgb(20, 20, 20);
			border-radius: 0.5px;
        }
		.button_rev:hover{
            background-color: #1d2731 ;
			color: white;
			}
		.button_rev:active{
			border-bottom: 2px solid rgb(100, 100, 100);
			border-right: 2px solid rgb(100, 100, 100);
			border-left: 2px solid rgb(20, 20, 20);
			border-top: 2px solid rgb(20, 20, 20);
		}
        .button_rev_w{
            text-decoration: none;
            font-size: 13px;
            color:black;
			cursor: pointer;
            background-color: white;
            padding: 5px 40px 5px 40px ;
			border-top: 2px solid rgb(100, 100, 100);
			border-left: 2px solid rgb(100, 100, 100);
			border-bottom: 2px solid rgb(20, 20, 20);
			border-right: 2px solid rgb(20, 20, 20);
			border-radius: 0.5px;
        }
		.button_rev_w:hover{
            background-color: #1d2731 ;
			color: white;
			}
		.button_rev_w:active{
			border-bottom: 2px solid rgb(100, 100, 100);
			border-right: 2px solid rgb(100, 100, 100);
			border-left: 2px solid rgb(20, 20, 20);
			border-top: 2px solid rgb(20, 20, 20);
		}
        /* For basket.html */
        .basket_list_section{
            margin-top: 80px;
        }
        .basket_items{
            padding: 0;
            margin: 0;
            display: block;
            box-sizing: border-box;
        }
        
        .basket_item{
            border: 1px solid #ddd;
            margin-top: -1px;
            background-color: #f6f6f6;
            padding: 12px;
            text-decoration: none;
            font-size: 18px;
            color: black;
            box-sizing: border-box;
            
        }
        .basket_item_detail{
            float: left;
            width: 20%;
            text-align: center;
            vertical-align: middle;
            margin: 0;
        }
        .basket_checkout{
            display: flex;
            float: left;
            width: 25%;
            text-align: center;
            vertical-align: middle;
            font-size: 20px;
            font-weight: 500;
            justify-content: space-around;
            background-color: whitesmoke;
            border: 1px solid #ddd;
            padding: 10px;
        }
        /* input[type=number]::-webkit-inner-spin-button, 
        input[type=number]::-webkit-outer-spin-button { 
            -webkit-appearance: none; 
        margin: 0; 
        } */
        input[type=number] {
        text-align: center;
        width: 30px;
        line-height: 25px;
        background-color: #1d2731;
        color: whitesmoke;
        }
        .empty_basket{
            font-weight:1000;
            font-size: 40px;
            text-align: center;
        }
        .empty_basket_text{
            margin-bottom: 10px;
        }
        .empty_basket_button{
            font-size: 30px;
        }
        .global_footer{
            position: fixed;
            padding: 0;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 30px;
            background: black;
        }
        .global_footer_items{
            text-align: center;
            position: relative;
        }
        .global_footer_item{
            font-size: 15px;
            color: white;
            margin: 5px;
        }
        .welcome-dir{
            box-sizing: border-box;

        }
        .welcome-dir-item{
            float: left;
            width: 50%;
            padding: 0px;
        }
    </style>
</head>
{% block content %}

{% endblock %}
<footer class="global_footer" style="z-index: 1">
    <div class="global_footer_items">
        <p class="global_footer_item">This page is a Django Project For Software Engineering Class | Programmers: Omid and Sorosh | 2021</p>
    </div>
</footer>
</html>

project/mnproject/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
<body style="background:url(https://i.pinimg.com/originals/85/6f/31/856f31d9f475501c7552c97dbe727319.jpg);">
    <header class="header">
		<nav class="nav">
			<ul class="nav__items">
                <li class="nav__item nav__home">
                    <a href="{% url 'productapp:home' %}">Home</a>
                </li>
				<li class="nav__item">
					<a href="{% url 'productapp:products' %}">Products</a>
				</li >
				<li class="nav__item">
					<a href="{% url 'productapp:basket' %}">Basket</a>
				</li>
                <li class="nav__item" >
					<a href="{% url 'admin:index' %}">Login</a>
				</li>
			</ul>
		</nav>
	</header>
    <section class="wellcome">
        <div>
            <p class="wellcome-div-p"">Wellcom to the Django Project</p>
        </div>
        <div>
            <p style="font-size: 20px; font-weight: 500;">In This Website, we provided you with fake tutorials for programming languages. Which you can add them to your basket. The amount is your Imaginations and removing it is also a choice.</p>
        </div>
        <div class="welcome-dir">
            <div  class="">
                <div class="products_section" style="margin-top: 35px;">
                <p style="text-align: center;font-size: 20px;">Here is some of our products</p>
                {% if products_list %}
                    {% for product in products_list|slice:":4" %}
                        <div class="products">
                            <div class="product" style="margin-top:22px;">
                                <img src="../{{product.product_pic}}" style="width:90px; border: 2px solid #051218;">
                                <p style="font-size: 22px;margin-bottom: 0;">{{product.products_name}}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No products avalable at this moment.</p>
                {% endif %}
            </div>
                <p style="text-align: center; display: block; background-color: white 0;" class="" ><a href="{% url 'productapp:products' %}" class="button_rev"> See More</a></p>
            </div>
        </div>
    </section>
    <section>
        <div>
            
        </div>
    </section>
</body>
{% endblock %}

project/mnproject/templates/productapp/basket.html
{% include 'base.html' %}
{% block content %}
<body style="background-color: white;">
    <header class="header">
		<nav class="nav">
			<ul class="nav__items">
                <li class="nav__item ">
                    <a href="{% url 'productapp:home' %}">Home</a>
                </li>
				<li class="nav__item">
					<a href="{% url 'productapp:products' %}">Products</a>
				</li >
				<li class="nav__item nav__home">
					<a href="{% url 'productapp:basket' %}">Basket</a>
				</li>
                <li class="nav__item" >
					<a href="{% url 'admin:index' %}">Login</a>
				</li>
			</ul>
		</nav>
	</header>  
<section class="basket_list_section">
    {% if basket_list %}
    <h1  style="text-align: center;">Shopping Basket</h1><hr>

        <ul class="basket_items">
            <li class="basket_item" style="background: 0; border: 0; font-weight: 500;">
                <p class="basket_item_detail">Product name</p>
                <p class="basket_item_detail">Amount</p>
                <p class="basket_item_detail">Price / Total Price</p>
                </form>
            </li>
        </ul>




        {% for product in basket_list %}
            <ul class="basket_items">
                <li class="basket_item">
                    <p class="basket_item_detail">{{product.products}}</p>
                    <p class="basket_item_detail">{{product.amount}}</p>
                    <p class="basket_item_detail">${{product.get_price}} / ${{product.get_total}}</p>
                    <!-- <p class="basket_item_detail">{{product.get_total}}</p> -->
                    <form class="basket_item_detail" style="float: right;" method="POST" action="{% url 'productapp:removefrombasket' product.id %}">
                        {% csrf_token %}
                        <input class="button_rev_w" type="submit" value="Remove">
                    </form>
                </li>
            </ul>
        {% endfor %}
        <div style="text-align: center;">
        <p class="basket_checkout" style="opacity: 0;;">-</p>
        <p class="basket_checkout" style="border-right: 0;padding-top: 14px;padding-bottom: 14px;">Total: ${{total}}</p>
        <p class="basket_checkout" style="border-left: 0; padding-top: 12px;padding-bottom: 12px;"><button class="button_rev_w" href="">Checkout</button></p>
        </div>
    {% else %}
    <div class="empty_basket">
        <p class="empty_basket_text">Your Basket is empty</p>
        <a href="{% url 'productapp:products' %}" class="button empty_basket_button">Continue Shopping</a>
    </div>
    {% endif %}
</section>
</body>
{% endblock %}

project/mnproject/templates/productapp/products.html
{% include 'base.html' %}
{% block content %}

<body class="body">
    <header class="header">
		<nav class="nav">
			<ul class="nav__items">
                <li class="nav__item ">
                    <a href="{% url 'productapp:home' %}">Home</a>
                </li>
				<li class="nav__item nav__home">
					<a href="{% url 'productapp:products' %}">Products</a>
				</li >
				<li class="nav__item ">
					<a href="{% url 'productapp:basket' %}">Basket</a>
				</li>
                <li class="nav__item" >
					<a href="{% url 'admin:index' %}">Login</a>
				</li>
			</ul>
		</nav>
	</header>   
    <section class="products_section" style="margin-bottom: 50px;">
        <h1 class="products_section_h1" style="color: #ffffff;">Our Tutorials</h1>       
            {% if products_list %}
                {% for product in products_list %}
                    <div class="products">
                        <div class="product">
                            <img src="../{{product.product_pic}}" style="width:200px; border: 2px solid #051218;">
                            <p style="font-size: 22px;">{{product.products_name}}</p>
                            <p>Price: {{product.price}}</p>
                            <p style="font-weight: bold;">{{product.note}}</p>
                            <form method="POST" action="{% url 'productapp:addtobasket' product.id %}">
                                {% csrf_token %}
                                <input min="1" value=1 type="number" name="amount">
                                <input class="button" type="submit" value="Add to Basket">
                            </form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No products avalable at this moment.</p>
            {% endif %}
    </section>
</body>
{% endblock %}